apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  namespace: "kfserving-test"
  name: "product-recommender"
spec:
  transformer:
        containers:
        - image: registry.gitlab.com/felix.exel/container_registry/kfserving/model-performance-monitoring
          name: user-container
          imagePullPolicy: Always
        imagePullSecrets:
          - name: gitlab
  predictor:
    serviceAccountName: "sa" # service account for aws credentials
    minReplicas: 1 # if 0: replica will scale down to 0 when there are no requests
    tensorflow:
      runtimeVersion: "2.4.0" #TensorFlow Serving Version
      storageUri: "s3://bucket-fex/0/719f2437c2a147d89ab6268cf7379cda/artifacts/saved_model/tfmodel/" # subfolder must contain numbers only for tf serving
    logger:
      mode: all
      url: http://broker-ingress.knative-eventing.svc.cluster.local/kfserving-test/product-recommender
