apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  namespace: kfserving-test
  name: autoencoder-recommender
spec:
  transformer:
        containers:
        - image: registry.gitlab.com/felix.exel/container_registry/kfserving/outlier-detection
          name: user-container
          imagePullPolicy: Always
        imagePullSecrets:
          - name: gitlab

  predictor:
    serviceAccountName: "sa" # service account for aws credentials
    minReplicas: 1 # if 0: replica will scale down to 0 when there are no requests
    tensorflow:
      runtimeVersion: "2.4.0" #TensorFlow Serving Version
      storageUri: "s3://bucket-fex/autoencoder_recommender/d052e637a7314c14a092585baf512672/" # subfolder must contain numbers only for tf serving
      resources:
        limits:
          cpu: "3" # cloud: 3, local 8
        requests:
          cpu: "1" # cloud: 1, local 2
