apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: concept-drift-trigger
  namespace: kfserving-test
spec:
  broker: product-recommender
  filter:
    attributes:
      type: org.kubeflow.serving.inference.request
  subscriber:
    uri: http://concept-drift-predictor-default.kfserving-test/v1/models/concept-drift:predict
